const droneFlightData = [
    {
      timestamp: "2025-04-12T09:15:30Z",
      missionCoordinator: "Alex Johnson",
      nameOfAircraft: "Falcon X-1",
      altitudeM: 152.4,
      windSpeedMS: 3.2,
      flightDistanceKm: 8.7,
      batteryTakeoffVoltage3s: 12.6,
      batteryTakeoffVoltage7s: 29.4,
      batteryTakeoffVoltage14s: 58.8,
      batteryLandingVoltage3s: 11.2,
      batteryLandingVoltage7s: 26.1,
      batteryLandingVoltage14s: 52.5,
      battery3sQty: 2,
      battery7sQty: 1,
      battery14sQty: 0,
      batteryHealth: "Good",
      droneOverallSystemHealthStatus: "Optimal",
      weatherConditions: "Clear",
      windConditions: "Light Breeze",
      temperatureC: "20-25",
      year: 2025,
      month: "April",
      week: 15,
      flightTime: "00:35:22",
      missionObjective: "Aerial Survey",
      description: "Standard grid pattern survey of northern agricultural zone",
      fuelLevelL: 1.8,
      weightKg: {
        before: 4.2,
        after: 4.0
      },
      fuelConsumptionL: 0.2,
      status: "Completed",
      comment: "Smooth flight, no issues encountered"
    },
    {
      timestamp: "2025-04-11T14:30:45Z",
      missionCoordinator: "Samantha Lee",
      nameOfAircraft: "Talon Pro",
      altitudeM: 241.3,
      windSpeedMS: 5.7,
      flightDistanceKm: 12.3,
      batteryTakeoffVoltage3s: 12.5,
      batteryTakeoffVoltage7s: 29.1,
      batteryTakeoffVoltage14s: 58.2,
      batteryLandingVoltage3s: 10.9,
      batteryLandingVoltage7s: 25.4,
      batteryLandingVoltage14s: 50.8,
      battery3sQty: 0,
      battery7sQty: 2,
      battery14sQty: 0,
      batteryHealth: "Good",
      droneOverallSystemHealthStatus: "Good",
      weatherConditions: "Partly Cloudy",
      windConditions: "Moderate",
      temperatureC: "15-20",
      year: 2025,
      month: "April",
      week: 15,
      flightTime: "00:42:10",
      missionObjective: "Infrastructure Inspection",
      description: "Power line inspection along eastern corridor",
      fuelLevelL: 2.4,
      weightKg: {
        before: 5.1,
        after: 4.7
      },
      fuelConsumptionL: 0.4,
      status: "Completed",
      comment: "Minor turbulence at 200m, otherwise nominal"
    },
    {
      timestamp: "2025-04-10T08:20:15Z",
      missionCoordinator: "Marco Rivera",
      nameOfAircraft: "Condor Heavy",
      altitudeM: 325.8,
      windSpeedMS: 2.1,
      flightDistanceKm: 18.6,
      batteryTakeoffVoltage3s: 12.6,
      batteryTakeoffVoltage7s: 29.3,
      batteryTakeoffVoltage14s: 58.9,
      batteryLandingVoltage3s: 10.7,
      batteryLandingVoltage7s: 25.2,
      batteryLandingVoltage14s: 50.1,
      battery3sQty: 0,
      battery7sQty: 0,
      battery14sQty: 2,
      batteryHealth: "Excellent",
      droneOverallSystemHealthStatus: "Optimal",
      weatherConditions: "Clear",
      windConditions: "Calm",
      temperatureC: "10-15",
      year: 2025,
      month: "April",
      week: 15,
      flightTime: "00:51:43",
      missionObjective: "Payload Delivery",
      description: "Medical supplies delivery to remote site",
      fuelLevelL: 3.5,
      weightKg: {
        before: 8.2,
        after: 5.8
      },
      fuelConsumptionL: 0.7,
      status: "Completed",
      comment: "Payload successfully delivered, return flight at higher altitude to conserve fuel"
    },
    {
      timestamp: "2025-04-09T16:45:20Z",
      missionCoordinator: "Jin Park",
      nameOfAircraft: "Swift Scout",
      altitudeM: 102.1,
      windSpeedMS: 7.8,
      flightDistanceKm: 5.4,
      batteryTakeoffVoltage3s: 12.4,
      batteryTakeoffVoltage7s: 29.0,
      batteryTakeoffVoltage14s: 58.1,
      batteryLandingVoltage3s: 10.5,
      batteryLandingVoltage7s: 24.6,
      batteryLandingVoltage14s: 49.2,
      battery3sQty: 4,
      battery7sQty: 0,
      battery14sQty: 0,
      batteryHealth: "Fair",
      droneOverallSystemHealthStatus: "Needs Maintenance",
      weatherConditions: "Overcast",
      windConditions: "Gusty",
      temperatureC: "5-10",
      year: 2025,
      month: "April",
      week: 15,
      flightTime: "00:22:38",
      missionObjective: "Security Patrol",
      description: "Perimeter surveillance of south campus",
      fuelLevelL: 1.2,
      weightKg: {
        before: 3.7,
        after: 3.6
      },
      fuelConsumptionL: 0.1,
      status: "Aborted",
      comment: "Mission terminated early due to high wind warnings"
    },
    {
      timestamp: "2025-04-08T11:10:05Z",
      missionCoordinator: "Emily Chen",
      nameOfAircraft: "Falcon X-2",
      altitudeM: 195.6,
      windSpeedMS: 4.3,
      flightDistanceKm: 15.2,
      batteryTakeoffVoltage3s: 12.5,
      batteryTakeoffVoltage7s: 29.2,
      batteryTakeoffVoltage14s: 58.4,
      batteryLandingVoltage3s: 11.0,
      batteryLandingVoltage7s: 25.7,
      batteryLandingVoltage14s: 51.5,
      battery3sQty: 0,
      battery7sQty: 1,
      battery14sQty: 1,
      batteryHealth: "Good",
      droneOverallSystemHealthStatus: "Good",
      weatherConditions: "Light Rain",
      windConditions: "Light",
      temperatureC: "15-20",
      year: 2025,
      month: "April",
      week: 14,
      flightTime: "00:45:15",
      missionObjective: "Wildlife Monitoring",
      description: "Tracking seasonal migration patterns in western reserve",
      fuelLevelL: 2.6,
      weightKg: {
        before: 5.8,
        after: 5.4
      },
      fuelConsumptionL: 0.4,
      status: "Completed",
      comment: "Visibility reduced during light precipitation but mission successful"
    },
    {
      timestamp: "2025-04-07T07:30:40Z",
      missionCoordinator: "David Thompson",
      nameOfAircraft: "Hummingbird Mini",
      altitudeM: 76.2,
      windSpeedMS: 1.5,
      flightDistanceKm: 3.2,
      batteryTakeoffVoltage3s: 12.6,
      batteryTakeoffVoltage7s: 0,
      batteryTakeoffVoltage14s: 0,
      batteryLandingVoltage3s: 11.4,
      batteryLandingVoltage7s: 0,
      batteryLandingVoltage14s: 0,
      battery3sQty: 1,
      battery7sQty: 0,
      battery14sQty: 0,
      batteryHealth: "Excellent",
      droneOverallSystemHealthStatus: "Optimal",
      weatherConditions: "Clear",
      windConditions: "Calm",
      temperatureC: "20-25",
      year: 2025,
      month: "April",
      week: 14,
      flightTime: "00:18:52",
      missionObjective: "Indoor Mapping",
      description: "3D mapping of north warehouse facility",
      fuelLevelL: 0.8,
      weightKg: {
        before: 1.9,
        after: 1.8
      },
      fuelConsumptionL: 0.1,
      status: "Completed",
      comment: "Perfect conditions for detailed indoor scanning"
    },
    {
      timestamp: "2025-04-06T15:55:22Z",
      missionCoordinator: "Rachel Adams",
      nameOfAircraft: "Talon Elite",
      altitudeM: 289.5,
      windSpeedMS: 6.2,
      flightDistanceKm: 20.7,
      batteryTakeoffVoltage3s: 0,
      batteryTakeoffVoltage7s: 29.4,
      batteryTakeoffVoltage14s: 58.8,
      batteryLandingVoltage3s: 0,
      batteryLandingVoltage7s: 24.9,
      batteryLandingVoltage14s: 49.7,
      battery3sQty: 0,
      battery7sQty: 0,
      battery14sQty: 2,
      batteryHealth: "Good",
      droneOverallSystemHealthStatus: "Good",
      weatherConditions: "Partly Cloudy",
      windConditions: "Moderate",
      temperatureC: "25-30",
      year: 2025,
      month: "April",
      week: 14,
      flightTime: "00:58:10",
      missionObjective: "Search and Rescue Exercise",
      description: "Training mission simulating person location in wilderness area",
      fuelLevelL: 4.2,
      weightKg: {
        before: 7.5,
        after: 6.7
      },
      fuelConsumptionL: 0.8,
      status: "Completed",
      comment: "Extended flight time due to complex search pattern"
    },
    {
      timestamp: "2025-04-05T10:40:15Z",
      missionCoordinator: "Carlos Mendez",
      nameOfAircraft: "Condor Standard",
      altitudeM: 213.4,
      windSpeedMS: 3.8,
      flightDistanceKm: 14.6,
      batteryTakeoffVoltage3s: 12.5,
      batteryTakeoffVoltage7s: 29.1,
      batteryTakeoffVoltage14s: 0,
      batteryLandingVoltage3s: 10.8,
      batteryLandingVoltage7s: 25.3,
      batteryLandingVoltage14s: 0,
      battery3sQty: 2,
      battery7sQty: 1,
      battery14sQty: 0,
      batteryHealth: "Fair",
      droneOverallSystemHealthStatus: "Good",
      weatherConditions: "Clear",
      windConditions: "Light",
      temperatureC: "20-25",
      year: 2025,
      month: "April",
      week: 14,
      flightTime: "00:39:45",
      missionObjective: "Agricultural Assessment",
      description: "Crop health monitoring and irrigation assessment",
      fuelLevelL: 2.5,
      weightKg: {
        before: 6.2,
        after: 5.8
      },
      fuelConsumptionL: 0.4,
      status: "Completed",
      comment: "Detected potential irrigation issue in southeast quadrant"
    },
    {
      timestamp: "2025-04-04T13:25:30Z",
      missionCoordinator: "Lisa Wong",
      nameOfAircraft: "Swift Scout Pro",
      altitudeM: 118.9,
      windSpeedMS: 2.7,
      flightDistanceKm: 7.8,
      batteryTakeoffVoltage3s: 12.6,
      batteryTakeoffVoltage7s: 29.4,
      batteryTakeoffVoltage14s: 0,
      batteryLandingVoltage3s: 11.1,
      batteryLandingVoltage7s: 25.8,
      batteryLandingVoltage14s: 0,
      battery3sQty: 2,
      battery7sQty: 1,
      battery14sQty: 0,
      batteryHealth: "Good",
      droneOverallSystemHealthStatus: "Good",
      weatherConditions: "Overcast",
      windConditions: "Light",
      temperatureC: "15-20",
      year: 2025,
      month: "April",
      week: 14,
      flightTime: "00:31:18",
      missionObjective: "Site Photography",
      description: "Construction progress documentation for east campus project",
      fuelLevelL: 1.6,
      weightKg: {
        before: 4.5,
        after: 4.3
      },
      fuelConsumptionL: 0.2,
      status: "Completed",
      comment: "Low light conditions required aperture adjustments"
    },
    {
      timestamp: "2025-04-03T09:05:10Z",
      missionCoordinator: "Michael Brown",
      nameOfAircraft: "Hummingbird Pro",
      altitudeM: 91.4,
      windSpeedMS: 1.2,
      flightDistanceKm: 4.5,
      batteryTakeoffVoltage3s: 12.4,
      batteryTakeoffVoltage7s: 0,
      batteryTakeoffVoltage14s: 0,
      batteryLandingVoltage3s: 11.2,
      batteryLandingVoltage7s: 0,
      batteryLandingVoltage14s: 0,
      battery3sQty: 2,
      battery7sQty: 0,
      battery14sQty: 0,
      batteryHealth: "Good",
      droneOverallSystemHealthStatus: "Good",
      weatherConditions: "Clear",
      windConditions: "Calm",
      temperatureC: "10-15",
      year: 2025,
      month: "April",
      week: 14,
      flightTime: "00:24:30",
      missionObjective: "Environmental Sampling",
      description: "Air quality measurement at industrial zone perimeter",
      fuelLevelL: 1.0,
      weightKg: {
        before: 3.2,
        after: 3.1
      },
      fuelConsumptionL: 0.1,
      status: "Completed",
      comment: "All samples collected successfully"
    }
  ];
  
  export default droneFlightData;